security check

diff --git a/.github/workflows/newflow.yml b/.github/workflows/newflow.yml
--- a/.github/workflows/newflow.yml
+++ b/.github/workflows/newflow.yml
@@ -22,3 +22,25 @@ jobs:
         with:
           # Target URL
           target: "https://bff.paymentgateway.ip-poc.com/bff/v1/gmo-charge"
+   
+      - uses: actions/checkout@v3
+
+      # Scan the code for security vulnerabilities using ZAP
+      - name: Scan for security issues with ZAP
+        uses: zaproxy/action-zap@latest
+        with:
+          zap-version: 2.12.0
+          targets: .
+          scan-policy: default
+          output-format: json
+          ascan-report: ZAP_Scan_Report.json
+
+      # Check the ZAP scan results for vulnerabilities
+      - name: Check the ZAP scan results
+        run: |
+          if [[ $(jq '.alerts | length' ZAP_Scan_Report.json) -gt 0 ]]; then
+            echo "Security scan failed. Detected security issues."
+            exit 1
+          fi
+
+          echo "Security scan passed. No issues found."
