dumbell

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -5,7 +5,6 @@ on:
   pull_request:
     branches: ['development']
   workflow_dispatch:
-
 jobs:
   build:
     runs-on: ubuntu-latest
@@ -18,26 +17,24 @@ jobs:
           target: 'https://front.questionnaire.ip-poc.com/app/survey'
 
       - name: Save Scan Report
-        run: mv zap-baseline-report.html myreport-$(date +"%Y%m%d%H%M%S").html
+        run: |
+          # Rename the report file to something unique
+          mv zap-baseline-report.html myreport-$(date +"%Y%m%d%H%M%S").html
 
       - name: Check for Issues in Scan Report
-        id: security_check
-        run: |
-          # Assuming you have a script to check the report for issues (e.g., using a tool like grep)
-          if grep -q 'Vulnerability Found' myreport*.html; then
-            echo "Security issues found in the scan report."
-            exit 1  # Exit with an error code to stop the workflow
-          else
-            echo "No security issues found in the scan report."
-          fi
-
-      - name: Publish Scan Report
-        if: steps.security_check.outcome == 'success'
-        uses: actions/upload-artifact@v2
+        uses: actions/github-script@v5
         with:
-          name: zap-scan-report
-          path: myreport*.html
+          script: |
+            const report = fs.readFileSync('myreport*.html', 'utf8');
+            if (report.includes('Vulnerability Found')) {
+              // Security issues found, fail the workflow
+              core.setFailed('Security issues found in the OWASP ZAP Baseline Scan.');
+            }
+          # Disable the `fail-fast` setting, so that the workflow will continue to execute even if this step fails
+          fail-fast: false
 
       - name: Fail the workflow if security issues found
-        if: steps.security_check.outcome == 'failure'
-        run: exit 1
+        if: ${{ failure() }}
+        run: |
+          echo "Security issues found in the OWASP ZAP Baseline Scan. Code push canceled."
+          exit 1
